version: "3.8"

services:
  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongocont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: mongodb://db:27017/inventory
  #   depends_on:
  #     - db

volumes:
  mongo-data:
